name = "navspheres"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liisqsEj23lcdgeS"
GITHUB_OWNER = "garcci"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav.gjqqq.com/api/auth"
NEXT_PUBLIC_API_URL="https://nav.gjqqq.com"

